### PR TITLE
Add tp5n pagesets with rich icon patch and zip both tp5n and tp6

### PR DESCRIPTION
**Pull request by Mardak**
This adds the tp5n zip and extracted files that I got from `./mach awsy-test --quick` then `cd ./obj/_tests/awsy/html/page_load_test/tp5n`

### CODE REVIEW

**Comment by Mardak** [comment]
Unclear if we should check in the .zip as tp6 doesn't. It also triggers GitHub's large file warning:
```
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File tp5n.zip is 77.97 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
```

**Comment by jmaher** [comment]
@rwood-moz I would like to merge this in, do you know how the large file storage works and if it will show up in a repo as normal?

**Comment by rwood-moz** [comment]
@jmaher No sorry I've never used git's large file storage :(

**Comment by jmaher** [comment]
Ok, let's look into it and consider using it.  Likewise if we can use the
large file proper with no problems.

**Comment by Mardak** [comment]
I have a separate branch https://github.com/Mardak/talos-pagesets/commits/rich-disable with Bug 1399320 patch r=jmaher applied that I'll set up with a PR depending on if we want the .zip in the repository or not.

**Comment by jmaher** [comment]
it looks like https://git-lfs.github.com/ is easy to use, lets do that with the edits applied- once we have this easily accessible via public, then we can make it easier to upload to tooltool.

**Comment by Mardak** [comment]
I tried to use LFS but seems to not like it when I push to my clone:
```
Git LFS: (0 of 3 files) 0 B / 161.97 MB                                                                                                                                                                      
batch response: @Mardak can not upload new objects to public fork Mardak/talos-pagesets
error: failed to push some refs to 'git@github.com:Mardak/talos-pagesets.git'
```

Sounds like only the main repository can accept pushes of large files once enabled?

**Comment by Mardak** [comment]
I updated this PR to have 3 commits: 1) add the original tp5n files that I extracted 2) zipped tp5n and tp6 3) applied patch and re-zipped tp5n

This is without LFS

**Comment by jmaher** [comment]
@rwood, do you want to merge this PR?

**Pull request merged**
